package com.mozip.server.policy.domain;

public enum PolicyAvailabilityReason {
    ALWAYS_OPEN,
    ALWAYS_APPLICATION_TYPE,
    WITHIN_APPLICATION_PERIOD,
    BEFORE_APPLICATION_PERIOD,
    AFTER_APPLICATION_PERIOD,
    CLOSED,
    DRAFT,
    SUSPENDED,
    UNKNOWN_APPLICATION_TYPE,
    MISSING_APPLICATION_PERIOD,
    INVALID_APPLICATION_PERIOD
}
